# Generated by Django 6.0.2 on 2026-04-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
