# Generated by Django 6.0.2 on 2026-04-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
